-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sobelFilter2024a\color_correct_core.vhd
-- Created: 2025-04-15 15:58:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: color_correct_core
-- Source Path: sobelFilter2024a/conv_core/color_correct_core
-- Hierarchy Level: 1
-- Model version: 8.65
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY color_correct_core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Video_in_0                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Video_in_1                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Video_in_2                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ctrl_hStart                       :   IN    std_logic;
        ctrl_hEnd                         :   IN    std_logic;
        ctrl_vStart                       :   IN    std_logic;
        ctrl_vEnd                         :   IN    std_logic;
        ctrl_valid                        :   IN    std_logic;
        Video_out_0                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Video_out_1                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        Video_out_2                       :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        valid_out_hStart                  :   OUT   std_logic;
        valid_out_hEnd                    :   OUT   std_logic;
        valid_out_vStart                  :   OUT   std_logic;
        valid_out_vEnd                    :   OUT   std_logic;
        valid_out_valid                   :   OUT   std_logic
        );
END color_correct_core;


ARCHITECTURE rtl OF color_correct_core IS

  -- Component Declarations
  COMPONENT Subsystem1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          channel_in_0                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          channel_in_1                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          channel_in_2                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Enable                          :   IN    std_logic;
          Video_out_0                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Video_out_1                     :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          Video_out_2                     :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem1
    USE ENTITY work.Subsystem1(rtl);

  -- Signals
  SIGNAL valid                            : std_logic;
  SIGNAL Subsystem1_out1_0                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Subsystem1_out1_1                : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Subsystem1_out1_2                : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_Subsystem1 : Subsystem1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              channel_in_0 => Video_in_0,  -- uint8
              channel_in_1 => Video_in_1,  -- uint8
              channel_in_2 => Video_in_2,  -- uint8
              Enable => valid,
              Video_out_0 => Subsystem1_out1_0,  -- uint8
              Video_out_1 => Subsystem1_out1_1,  -- uint8
              Video_out_2 => Subsystem1_out1_2  -- uint8
              );

  valid <= ctrl_valid;

  Video_out_0 <= Subsystem1_out1_0;

  Video_out_1 <= Subsystem1_out1_1;

  Video_out_2 <= Subsystem1_out1_2;

  valid_out_hStart <= ctrl_hStart;

  valid_out_hEnd <= ctrl_hEnd;

  valid_out_vStart <= ctrl_vStart;

  valid_out_vEnd <= ctrl_vEnd;

  valid_out_valid <= ctrl_valid;

END rtl;

