vlib work
vcom  conv_core_pkg.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  slicer.vhd
vcom  Subsystem1.vhd
vcom  gaussian_conv_core.vhd
vcom  Subsystem1_block.vhd
vcom  just_gray_core.vhd
vcom  slicer_block.vhd
vcom  Subsystem1_block1.vhd
vcom  sobel_horz_conv_core.vhd
vcom  slicer_block1.vhd
vcom  Subsystem1_block2.vhd
vcom  sobel_vert_conv_core.vhd
vcom  slicer_block2.vhd
vcom  slicer1.vhd
vcom  Subsystem2.vhd
vcom  sqrt_threshold.vhd
vcom  conv_core.vhd
vcom  conv_core_tb_pkg.vhd
vcom  conv_core_tb.vhd
