cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'red';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Delay1','user1');
hilite_system('sobelFilter2024a/conv_core/sobel_vert_conv_core/Delay1','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Constant','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Reshape','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay10','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay11','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay12','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay13','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay14','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay15','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay17','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay18','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay19','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay20','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay4','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay5','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay6','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay7','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay8','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Delay9','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Mux','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product1','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product10','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product11','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product12','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product13','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product14','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product16','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product17','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product18','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product2','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product3','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product4','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product5','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product7','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product8','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Product9','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum1','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum2','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum3','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum5','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum6','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum7','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/Sum8','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer/Delay3','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer/Delay5','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer/Delay6','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer/Line buffer1','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer1/Delay3','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer1/Delay5','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer1/Delay6','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer1/Line buffer1','user1');
hilite_system('sobelFilter2024a/conv_core/sqrt_threshold/Transpose','user1');
