open_system('sobelFilter2024a');
open_system('gm_sobelFilter2024a');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 'user2');
annotate_port('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 'user2');
annotate_port('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/gaussian_conv_core/Reshape', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/gaussian_conv_core/Reshape', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/gaussian_conv_core/Reshape', 'user2');
annotate_port('sobelFilter2024a/conv_core/gaussian_conv_core/Reshape', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/gaussian_conv_core/t', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/gaussian_conv_core/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/gaussian_conv_core/Transpose', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/gaussian_conv_core/Transpose', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/gaussian_conv_core/Transpose', 'user2');
annotate_port('sobelFilter2024a/conv_core/gaussian_conv_core/Transpose', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core/Reshape', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core/Reshape', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_horz_conv_core/Reshape', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_horz_conv_core/Reshape', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core/t', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core/Transpose', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core/Transpose', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_horz_conv_core/Transpose', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_horz_conv_core/Transpose', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Reshape', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Reshape', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Reshape', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Reshape', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/t', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Transpose', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Transpose', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Transpose', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_horz_conv_core_alt/Transpose', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core/Reshape', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core/Reshape', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_vert_conv_core/Reshape', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_vert_conv_core/Reshape', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core/t', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core/Transpose', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core/Transpose', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_vert_conv_core/Transpose', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_vert_conv_core/Transpose', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Reshape', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Reshape', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Reshape', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Reshape', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/t', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/t', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Transpose', 'user2');
annotate_port('gm_sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Transpose', 1, 1, 'Block not characterized');
hilite_system('sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Transpose', 'user2');
annotate_port('sobelFilter2024a/conv_core/sobel_vert_conv_core_alt/Transpose', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 'user2');
annotate_port('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 'user2');
annotate_port('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max1', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 'user2');
annotate_port('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 'user2');
annotate_port('sobelFilter2024a/conv_core/color_correct_core/Subsystem1/Max2', 1, 1, 'Block not characterized');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
