-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sobelFilter2024a\just_gray_core.vhd
-- Created: 2025-04-09 17:29:30
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: just_gray_core
-- Source Path: sobelFilter2024a/conv_core/just_gray_core
-- Hierarchy Level: 1
-- Model version: 8.45
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY just_gray_core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Video_in_0                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Video_in_1                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Video_in_2                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ctrl_hStart                       :   IN    std_logic;
        ctrl_hEnd                         :   IN    std_logic;
        ctrl_vStart                       :   IN    std_logic;
        ctrl_vEnd                         :   IN    std_logic;
        ctrl_valid                        :   IN    std_logic;
        Video_out                         :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        valid_out_hStart                  :   OUT   std_logic;
        valid_out_hEnd                    :   OUT   std_logic;
        valid_out_vStart                  :   OUT   std_logic;
        valid_out_vEnd                    :   OUT   std_logic;
        valid_out_valid                   :   OUT   std_logic
        );
END just_gray_core;


ARCHITECTURE rtl OF just_gray_core IS

  -- Component Declarations
  COMPONENT Subsystem1_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          channel_in_0                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          channel_in_1                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          channel_in_2                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Enable                          :   IN    std_logic;
          Video_out                       :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem1_block
    USE ENTITY work.Subsystem1_block(rtl);

  -- Signals
  SIGNAL valid                            : std_logic;
  SIGNAL Subsystem1_out1                  : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_Subsystem1 : Subsystem1_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              channel_in_0 => Video_in_0,  -- uint8
              channel_in_1 => Video_in_1,  -- uint8
              channel_in_2 => Video_in_2,  -- uint8
              Enable => valid,
              Video_out => Subsystem1_out1  -- uint8
              );

  valid <= ctrl_valid;

  Video_out <= Subsystem1_out1;

  valid_out_hStart <= ctrl_hStart;

  valid_out_hEnd <= ctrl_hEnd;

  valid_out_vStart <= ctrl_vStart;

  valid_out_vEnd <= ctrl_vEnd;

  valid_out_valid <= ctrl_valid;

END rtl;

