-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sobelFilter2024a\slicer_block4.vhd
-- Created: 2025-04-15 15:58:44
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: slicer_block4
-- Source Path: sobelFilter2024a/conv_core/sqrt_threshold/Subsystem2/slicer
-- Hierarchy Level: 3
-- Model version: 8.65
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY slicer_block4 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        channel_in                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        out_5                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END slicer_block4;


ARCHITECTURE rtl OF slicer_block4 IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_generic
    GENERIC( AddrWidth                    : integer;
             DataWidth                    : integer
             );
    PORT( clk                             :   IN    std_logic;
          enb                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(DataWidth - 1 DOWNTO 0);  -- generic width
          wr_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          wr_en                           :   IN    std_logic;  -- ufix1
          rd_addr                         :   IN    std_logic_vector(AddrWidth - 1 DOWNTO 0);  -- generic width
          dout                            :   OUT   std_logic_vector(DataWidth - 1 DOWNTO 0)  -- generic width
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SimpleDualPortRAM_generic
    USE ENTITY work.SimpleDualPortRAM_generic(rtl);

  -- Signals
  SIGNAL channel_in_unsigned              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay1_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay4_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Line_buffer_regin                : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Line_buffer_waddr                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Line_buffer_wrenb                : std_logic;  -- ufix1
  SIGNAL Line_buffer_raddr                : unsigned(9 DOWNTO 0);  -- ufix10
  SIGNAL Line_buffer_regout               : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL Line_buffer_regout_unsigned      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Line_buffer_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Delay2_out1                      : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  u_ShiftRegisterRAM : SimpleDualPortRAM_generic
    GENERIC MAP( AddrWidth => 10,
                 DataWidth => 8
                 )
    PORT MAP( clk => clk,
              enb => enb,
              wr_din => std_logic_vector(Line_buffer_regin),
              wr_addr => std_logic_vector(Line_buffer_waddr),
              wr_en => Line_buffer_wrenb,  -- ufix1
              rd_addr => std_logic_vector(Line_buffer_raddr),
              dout => Line_buffer_regout
              );

  channel_in_unsigned <= unsigned(channel_in);

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay1_out1 <= channel_in_unsigned;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay4_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay4_out1 <= Delay1_out1;
      END IF;
    END IF;
  END PROCESS Delay4_process;


  -- Input register for RAM-based shift register Line buffer
  Line_buffer_reginc_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Line_buffer_regin <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Line_buffer_regin <= Delay4_out1;
      END IF;
    END IF;
  END PROCESS Line_buffer_reginc_process;


  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 747
  -- Write address counter for RAM-based shift register Line buffer
  Line_buffer_wr_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Line_buffer_waddr <= to_unsigned(16#000#, 10);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Line_buffer_waddr >= to_unsigned(16#2EB#, 10) THEN 
          Line_buffer_waddr <= to_unsigned(16#000#, 10);
        ELSE 
          Line_buffer_waddr <= Line_buffer_waddr + to_unsigned(16#001#, 10);
        END IF;
      END IF;
    END IF;
  END PROCESS Line_buffer_wr_process;


  Line_buffer_wrenb <= '1';

  -- Count limited, Unsigned Counter
  --  initial value   = 1
  --  step value      = 1
  --  count to value  = 747
  -- Read address counter for RAM-based shift register Line buffer
  Line_buffer_rd_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Line_buffer_raddr <= to_unsigned(16#001#, 10);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF Line_buffer_raddr >= to_unsigned(16#2EB#, 10) THEN 
          Line_buffer_raddr <= to_unsigned(16#000#, 10);
        ELSE 
          Line_buffer_raddr <= Line_buffer_raddr + to_unsigned(16#001#, 10);
        END IF;
      END IF;
    END IF;
  END PROCESS Line_buffer_rd_process;


  Line_buffer_regout_unsigned <= unsigned(Line_buffer_regout);

  -- Output register for RAM-based shift register Line buffer
  Line_buffer_regoutc_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Line_buffer_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Line_buffer_out1 <= Line_buffer_regout_unsigned;
      END IF;
    END IF;
  END PROCESS Line_buffer_regoutc_process;


  Delay2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay2_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Delay2_out1 <= Line_buffer_out1;
      END IF;
    END IF;
  END PROCESS Delay2_process;


  out_5 <= std_logic_vector(Delay2_out1);

END rtl;

