-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sobelFilter2024a\sobel_horz_conv_core.vhd
-- Created: 2025-04-09 17:29:30
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: sobel_horz_conv_core
-- Source Path: sobelFilter2024a/conv_core/sobel_horz_conv_core
-- Hierarchy Level: 1
-- Model version: 8.45
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.conv_core_pkg.ALL;

ENTITY sobel_horz_conv_core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Video_in                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ctrl_valid                        :   IN    std_logic;
        Video_out                         :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END sobel_horz_conv_core;


ARCHITECTURE rtl OF sobel_horz_conv_core IS

  -- Component Declarations
  COMPONENT Subsystem1_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          channel_in                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          coeffs_0                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_1                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_2                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_3                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_4                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_5                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_6                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_7                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          coeffs_8                        :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En12
          Enable                          :   IN    std_logic;
          Video_out                       :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Subsystem1_block1
    USE ENTITY work.Subsystem1_block1(rtl);

  -- Signals
  SIGNAL c9_Constant_out1                 : vector_of_signed16(0 TO 8);  -- sfix16_En12 [9]
  SIGNAL Constant_out1                    : matrix_of_signed16(0 TO 2, 0 TO 2);  -- sfix16_En12 [3x3]
  SIGNAL Transpose_out1                   : matrix_of_signed16(0 TO 2, 0 TO 2);  -- sfix16_En12 [3x3]
  SIGNAL Reshape_out1                     : vector_of_signed16(0 TO 8);  -- sfix16_En12 [9]
  SIGNAL valid                            : std_logic;
  SIGNAL Subsystem1_out1                  : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  -- Coefficients Constants Block

  u_Subsystem1 : Subsystem1_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              channel_in => Video_in,  -- uint8
              coeffs_0 => std_logic_vector(Reshape_out1(0)),  -- sfix16_En12
              coeffs_1 => std_logic_vector(Reshape_out1(1)),  -- sfix16_En12
              coeffs_2 => std_logic_vector(Reshape_out1(2)),  -- sfix16_En12
              coeffs_3 => std_logic_vector(Reshape_out1(3)),  -- sfix16_En12
              coeffs_4 => std_logic_vector(Reshape_out1(4)),  -- sfix16_En12
              coeffs_5 => std_logic_vector(Reshape_out1(5)),  -- sfix16_En12
              coeffs_6 => std_logic_vector(Reshape_out1(6)),  -- sfix16_En12
              coeffs_7 => std_logic_vector(Reshape_out1(7)),  -- sfix16_En12
              coeffs_8 => std_logic_vector(Reshape_out1(8)),  -- sfix16_En12
              Enable => valid,
              Video_out => Subsystem1_out1  -- uint8
              );

  c9_Constant_out1(0) <= to_signed(16#1000#, 16);
  c9_Constant_out1(1) <= to_signed(16#2000#, 16);
  c9_Constant_out1(2) <= to_signed(16#1000#, 16);
  c9_Constant_out1(3) <= to_signed(16#0000#, 16);
  c9_Constant_out1(4) <= to_signed(16#0000#, 16);
  c9_Constant_out1(5) <= to_signed(16#0000#, 16);
  c9_Constant_out1(6) <= to_signed(-16#1000#, 16);
  c9_Constant_out1(7) <= to_signed(-16#2000#, 16);
  c9_Constant_out1(8) <= to_signed(-16#1000#, 16);

  Constant_out1_gen1: FOR d1 IN 0 TO 2 GENERATE
    Constant_out1_gen: FOR d0 IN 0 TO 2 GENERATE
      Constant_out1(d0, d1) <= c9_Constant_out1(d0 + (d1 * 3));
    END GENERATE;
  END GENERATE;


  Transpose_out1_gen: FOR t_1 IN 0 TO 2 GENERATE
    Transpose_out1_gen_1: FOR t_0 IN 0 TO 2 GENERATE
      Transpose_out1(t_0, t_1) <= Constant_out1(t_1, t_0);
    END GENERATE Transpose_out1_gen_1;
  END GENERATE Transpose_out1_gen;


  Reshape_out1_gen1: FOR d1 IN 0 TO 2 GENERATE
    Reshape_out1_gen: FOR d0 IN 0 TO 2 GENERATE
      Reshape_out1(d0 + (d1 * 3)) <= Transpose_out1(d0, d1);
    END GENERATE;
  END GENERATE;

  valid <= ctrl_valid;

  Video_out <= Subsystem1_out1;

END rtl;

